### ISSUE TITLE
Add James Grunewald to yjaf repos with write access (dev)

### ISSUE THREAD

**Issue by gregi2n** [ministryofjustice/github-collaborators#103]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

All yjaf-* repos excluding yjaf-devops-infrastructure

## What is the GitHub username of the person who needs access?

JWGNPS

## What is their full name?

James Grunewald

## What is their email address?

james.grunewald@northgateps.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

NPS (northgate)

## What level of access should they have?

- [ ] Read
- [ ] Triage
- [X] Write
- [ ] Maintain
- [ ] Admin

## Why is this access being requested?

New dev needs access to make app changes

## Which MoJ team/person is responsible for this request?

Greg Whiting - greg.whiting@northgateps.com - Devops for northgate

## Review date

2021-12-31

**Comment by digitalronin** [comment]
yjaf-app-template
yjaf-assets
yjaf-auth
yjaf-bands
yjaf-bed-unlock
yjaf-case
yjaf-cmm
yjaf-conversions
yjaf-csppi
yjaf-dal
yjaf-documents
yjaf-gateway
yjaf-infra-aws-mgmt
yjaf-mule-hub-connector
yjaf-mule-mis-processor
yjaf-nginx-gateway
yjaf-nginx-pentaho
yjaf-placements
yjaf-pnomis
yjaf-refdata
yjaf-returns
yjaf-sentences
yjaf-transfers
yjaf-ui
yjaf-utilities
yjaf-views
yjaf-workflow
yjaf-yp

**Comment by digitalronin** [comment]
Skipping yjaf-infra-aws-mgmt and yjaf-pnomis because no collaborators at all are currently defined on those repositories.
