### ISSUE TITLE
Please create an outside collaborator pull request 

### ISSUE THREAD

**Issue by olusegunonec** [ministryofjustice/github-collaborators#1069]
### username

olusegnnec

### name

Olusegun Odunukan

### email

olusegun.odunukan@necsws.com

### org

Nec Software Solutions

### reason

To update codebase

### added_by

gareth.davies@digital.justice.gov.uk

### review_after

2022-07-31

### permission

maintain

### repositories

yjaf-sentences

**Comment by NickWalt01** [comment]
Hi @olusegunonec the date is wrong within the review_after date should be YYYY-MM-DD and the repositories should be just yjaf-sentences and the added by isn't antony.bishop@digital.justice.gov.uk, it would need to be someone who works with the NEC team, ie Gareth Davies <gareth.davies@digital.justice.gov.uk>

**Comment by olusegunonec** [comment]
That's has now been updated

**Comment by NickWalt01** [comment]
Thanks

**Comment by NickWalt01** [comment]
Hello @
