### ISSUE TITLE
Add extra NPS devops users to yjaf repos

### ISSUE THREAD

**Issue by gregi2n** [ministryofjustice/github-collaborators#107]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

yjaf-assets
yjaf-auth
yjaf-bands
yjaf-bed-unlock
yjaf-case
yjaf-cmm
yjaf-conversions
yjaf-csppi
yjaf-dal
yjaf-documents
yjaf-gateway
yjaf-placements
yjaf-refdata
yjaf-returns
yjaf-sentences
yjaf-transfers
yjaf-ui
yjaf-utilities
yjaf-views
yjaf-workflow
yjaf-yp
yjsm-hub
yjsm-hubadmin

## What is the GitHub username of the person who needs access?

brbaje-dev
henrycarteruk

## What is their full name?

Ben Bajek
Henry Carter

## What is their email address?

ben.bajek@northgateps.com
henry.carter@northgateps.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

NPS

## What level of access should they have?

- [ ] Read
- [ ] Triage
- [ ] Write
- [ ] Maintain
- [X] Admin

## Why is this access being requested?

Additional devops member needed for projects

## Which MoJ team/person is responsible for this request?

Greg Whiting (current devops)

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

Greg Whiting greg.whiting@northgateps.com

## Review date

2021-12-01

**Comment by AntonyBishop** [comment]
Hi @gregi2n just awaiting PR to be approved and merged.
