### ISSUE TITLE
Request addition of external collaborator.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/github-collaborators#108]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

security-guidance

## What is the GitHub username of the person who needs access?

tomdMOJ

## What is their full name?

Tom Dumic

## What is their email address?

tom.dumic@digital.justice.gov.uk

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

UK MoJ Digital and Technology

## What level of access should they have?

- Write

## Why is this access being requested?

Tom is a technical writer, working on the security policy and guidance content.

## Which MoJ team/person is responsible for this request?

This should be in the form `Awesome Team <awesome.team@digital.justice.gov.uk>`.

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

Adrian Warman <adrian.warman@digital.justice.gov.uk>

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

2022-01-31

**Comment by AntonyBishop** [comment]
@warmanaMOJ PR raised. Just awaiting for it to be approved so it can be merged.
