### ISSUE TITLE
Access to repos has been removed when still defined in external collaborators

### ISSUE THREAD

**Issue by monotypical** [ministryofjustice/github-collaborators#1093]
Hello!

I have had my access to Bichard7 repositories removed while still in the external collaborators file, e.g. I am defined in https://github.com/ministryofjustice/github-collaborators/blob/main/terraform/bichard7-next.tf#L35 however I am unable to access the private repo.

This issue started occurring very recently, and I had access yesterday evening.

I think something may have gone wrong with how these permissions are applied, could somebody please check if this is in error?

**Comment by AntonyBishop** [comment]
Hi @monotypical (Alice),

Have added you back on. Am investigating the issue.
