### ISSUE TITLE
Acccess request for new dev

### ISSUE THREAD

**Issue by gregi2n** [ministryofjustice/github-collaborators#1155]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the terraform/ directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

Which MoJ repository are you requesting access to (e.g. money-to-prisoners)?
All yjaf-* repos and yjsm-*

What is the GitHub username of the person who needs access?
markstanley-nps

What is their full name?
Mark Stanley

What is their email address?
mark.stanley@necsws.com

What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?
NECSWS

What level of access should they have?
Developer

Why is this access being requested?
dev needs access to make app changes

Which MoJ team/person is responsible for this request?
Greg Whiting - [greg.whiting@northgateps.com](mailto:greg.whiting@northgateps.com) - Devops for necws

Review date
2024-02-15

**Comment by NickWalt01** [comment]
Hi @gregi2n, for access it should state permission access ie read, write, admin, which level is required? Also for MoJ person it needs someone with a justice.gov.uk or digital.justice.gov.uk email address, is there someone ?

**Comment by gregi2n** [comment]
Hi, sorry I missed that. Actually this is read only access.

The MOJ email I don't have, everyone on the team has a necsws.com email. But a lot of requests do go through Mick.Ewers@yjb.gov.uk

is that acceptable?

**Comment by NickWalt01** [comment]
Yes thank you will get a PR created

**Comment by NickWalt01** [comment]
Hi Greg, am waiting upon Mick's approval before being able to allow Mark access to the repo's
