### ISSUE TITLE
Access Renewal - Andrew Richards

### ISSUE THREAD

**Issue by joharveynec** [ministryofjustice/github-collaborators#1513]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository/s are you requesting access to (e.g. `money-to-prisoners`)?

yjaf-assets
yjaf-auth
yjaf-bands
yjaf-bed-unlock
yjaf-case
yjaf-cmm
yjaf-conversions
yjaf-dal
yjaf-datateam
yjaf-documents
yjaf-gateway
yjaf-gateway-proxy
yjaf-mule-hub-connector
yjaf-placements
yjaf-refdata
yjaf-returns
yjaf-sentences
yjaf-serious-incidents
yjaf-transfers
yjaf-transitions
yjaf-ui
yjaf-views
yjaf-workflow
yjaf-yp
yjsm-hub
yjsm-hubadmin
yjsm-hub-svc
yjaf-app-template
yjaf-csppi
yjaf-mule-miss-processor
yjaf-nginx-gateway

## What is the GitHub username of the person who needs access?

AndrewTRichards

## What is their full name?

Andrew Richards

## What is their email address?

andrew.richards1@necsws.com

## What company/organisation do they belong to (e.g. "Department for Education")?

NEC SWS / YJAF

## What level of access should they have?

 Admin

## Why is this access being requested?

Existing developer - renewing review_after date

## Which MoJ team/person is responsible for this request? This must be someone with a "*.justice.gov.uk" or "*.digital.justice.gov.uk" email address.

This should be in the form `Awesome Team <awesome.team@digital.justice.gov.uk>` or `awesome.team@digital.justice.gov.uk`.

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

[antony.bishop@digital.justice.gov.uk](mailto:antony.bishop@digital.justice.gov.uk)

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

2024-06-01

**Comment by NickWalt01** [comment]
Will add user back in
