### ISSUE TITLE
Please create an outside collaborator/s pull request

### ISSUE THREAD

**Issue by mshodge** [ministryofjustice/github-collaborators#1517]
### usernames

sdj-moj
simonytta

### names

Stephen Jobling
Simona Treivase

### emails

stephen.jobling@digital.justice.gov.uk
simona.treivase@justice.gov.uk

### org

Ministry of Justice

### reason

Agilisys project to be added to data-and-insights-hub team 

### added_by

Michael Hodge michael.hodge@digital.justice.gov.uk

### review_after

2024-06-01

### permission

maintain

### repositories

data-and-insights-hub team

**Comment by NickWalt01** [comment]
Hello @mshodge the repository field has a repo called 'data-and-insights-hub team' that does not exist on this Org, what repo should it be? Collaborators cannot be added to teams on github

**Comment by mshodge** [comment]
@NickWalt01 ah thanks Nick. I might need to ask both users to join the org instead then as we need them to be added to a team rather than directly to repos, I think. Let me double check before I close this.

**Comment by NickWalt01** [comment]
Both users have a digital and justice account so it should be okay for them to join the Org
