### ISSUE TITLE
Please create an outside collaborator/s pull request

### ISSUE THREAD

**Issue by harichintala1** [ministryofjustice/github-collaborators#1591]
### usernames

shaun-bsi

### names

**Shaun Dundavan**

### emails

shaun.dundavan@bsigroup.com

### org

digital-prison-reporting

### reason

IT Health Check

### added_by

hari.chintala@digital.justice.gov.uk

### review_after

2023-08-30

### permission

push

### repositories

digital-prison-reporting-jobs

**Comment by NickWalt01** [comment]
Hi Hari thanks we will get that merged in, the automation closes this issue automatically when every things went okay and the new issue passed our tests
