### ISSUE TITLE
Require access to all microservices

### ISSUE THREAD

**Issue by stephenhobden** [ministryofjustice/github-collaborators#1606]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository/s are you requesting access to (e.g. `money-to-prisoners`)?

<yjaf-assets
yjaf-yp
yjaf-workflow
yjaf-views
yjaf-placements
yjaf-refdata
yjaf-transfers
yjaf-conversions
yjaf-sentences
yjaf-returns
yjaf-gateway
yjaf-documents
yjaf-dal
yjaf-case
yjaf-bed-unlock
yjaf-bands
yjaf-auth
yjaf-transitions
yjaf-serious-incidents
yjaf-mule-hub-connector
yjaf-mule-mis-processor>

## What is the GitHub username of the person who needs access?

 Stephenhobden

## What is their full name?

 Stephen  Hobden

## What is their email address?

 stephen.hobden@necsws.com

## What company/organisation do they belong to (e.g. "Department for Education")? NECSWS

 NECSWS

## What level of access should they have?

- [ ] Read
- [ ] Triage
- [ ] Write
- [ ] Maintain
- [X] Admin

## Why is this access being requested?

 Want to amend logging settings for all microservices

## Which MoJ team/person is responsible for this request? This must be someone with a "*.justice.gov.uk" or "*.digital.justice.gov.uk" email address. Anthony.bishop@digital.justice.gov.uk

This should be in the form `Awesome Team <awesome.team@digital.justice.gov.uk>` or `awesome.team@digital.justice.gov.uk`.

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

 Anthony.bishop@digital.justice.gov.uk

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

 11/07/24

**Comment by stephenhobden** [comment]
Who should the approve be of not Anthony, my colleagues say they selected him last time.
For some reason, repositories not pasted. They are below, cheers

yjaf-assets
yjaf-yp
yjaf-workflow
yjaf-views
yjaf-placements
yjaf-refdata
yjaf-transfers
yjaf-conversions
yjaf-sentences
yjaf-returns
yjaf-gateway
yjaf-documents
yjaf-dal
yjaf-case
yjaf-bed-unlock
yjaf-bands
yjaf-auth
yjaf-transitions
yjaf-serious-incidents
yjaf-mule-hub-connector
yjaf-mule-mis-processor

**Comment by stephenhobden** [comment]
Some minor amendments, as missing a few repositories. The full list below, cheers

yjaf-assets
yjaf-auth
yjaf-bands
yjaf-bed-unlock
yjaf-case
yjaf-cmm
yjaf-conversions
yjaf-dal
yjaf-datateam
yjaf-documents
yjaf-gateway
yjaf-gateway-proxy
yjaf-mule-hub-connector
yjaf-mule-mis-processor
yjaf-placements
yjaf-refdata
yjaf-returns
yjaf-sentences
yjaf-serious-incidents
yjaf-serious-incidents.zip
yjaf-transfers
yjaf-transitions
yjaf-ui
yjaf-views
yjaf-workflow
yjaf-yp
yjsm-hub
yjsm-hub-svc
yjsm-hubadmin

**Comment by NickWalt01** [comment]
Sure, do you need to be added to the repositories that have been archived (these have not been updated for over 1.5 years) ?

**Comment by stephenhobden** [comment]
Ideally all archives, likely I won't need these older ones, but they could still be valid as no updates necessary. Cheers

**Comment by NickWalt01** [comment]
Invites to the repo's should be sent soon
