### ISSUE TITLE
Please create an outside collaborator pull request 

### ISSUE THREAD

**Issue by armoj** [ministryofjustice/github-collaborators#1775]
### usernames

BSI0714
JP-BSI

### names

Daniel Elliott
Joe Phee

### emails

Daniel.elliott@bsigroup.com
joseph.phee@bsigroup.com

### org

BSI

### reason

CICA IT Health Check

### added_by

adrian.roworth@digitial.justice.gov.uk

### review_after

2023-10-13

### permission

pull

### repositories

cloud-platform-environments

**Comment by NickWalt01** [comment]
Hello @armoj  the access is only pull, so the users will not be able to push any changes to the repository, is that the expectaction? Do this users need to be in a GH team, if so they will also need to be made full org members

**Comment by armoj** [comment]
What we are trying to achieve here is let 2 external tested to get access to our pods for in IT Health Check. Only read access is needed here. They would would need to be in our `cica` team.

relevant Slack thread is here: https://mojdt.slack.com/archives/C57UPMZLY/p1694701275615069

**Comment by NickWalt01** [comment]
Okay will add them as collaborators then once they have accepted the invites make them full org members so that they can get access / added to the team

**Comment by NickWalt01** [comment]
users added as outside collaborators
