### ISSUE TITLE
Stuart Westbrook hmpps-jenkins-admin GROUP access

### ISSUE THREAD

**Issue by izzy-ol** [ministryofjustice/github-collaborators#182]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

[All repos under hmpps-jenkins-admin group, 113 in total] So could this user be added to the GROUP hmpps-jenkins-admin 

## What is the GitHub username of the person who needs access?

swestb

## What is their full name?

Stuart Westbrook

## What is their email address?

stuart.westbrook@adrocgroup.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

Adroc Group

## What level of access should they have?

- [ ] Read
- [ ] Triage
- [ ] Write
- [ ] Maintain
- [x] Admin

## Why is this access being requested?

Stuart is a new member of the team and will require the same level of access to the repos as the rest of the developers in this group

## Which MoJ team/person is responsible for this request?

Probation Infrastructure AWS Team, awssupportteam@digital.justice.gov.uk

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

Max Lakanu maximillian.lakanu@digital.justice.gov.uk

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

2022-05-21

**Comment by jakemulley** [comment]
👋🏼 Hi @izzy-ol!

Unfortunately collaborators can't be part of teams, so I've replicated the `hmpps-jenkins-admin` permissions for `swestb` in PR #185.
