### ISSUE TITLE
Request to delete repo

### ISSUE THREAD

**Issue by javaidarshadnec** [ministryofjustice/github-collaborators#1822]
Hi,
Could I please request deletion of an old deprecated repo - https://github.com/ministryofjustice/yjaf-csppi
Regards,
Javaid.

**Comment by AntonyBishop** [comment]
Hi @javaidarshadnec I'll remove the collaborators before we archive the repo.

**Comment by AntonyBishop** [comment]
@javaidarshadnec the repo has now been archived. Any issues please let us know.
