### ISSUE TITLE
Access to yjaf-pnomis

### ISSUE THREAD

**Issue by gregi2n** [ministryofjustice/github-collaborators#187]
Please supply all the requested information, so that your request can be processed as quickly as possible.

Which MoJ repository are you requesting access to (e.g. money-to-prisoners)?
yjaf-pnomis

What is the GitHub username of the person who needs access?
AndrewRichards72
boydingham
gregi2n

What is their full name?
Andrew Richards
boyd cunningham
Greg Whiting

What is their email address?
andrew.richards@northgateps.com
Boyd.cunningham@northgateps.com
greg.whiting@northgateps.com

What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?
NPS (Northgate PS), formerly i2N, soon to be NEC Software Solutions.

What level of access should they have?
boydingham - Developer
AndrewRichards72 and gregi2n - Admin

Why is this access being requested?
dev needs access to make app changes

Which MoJ team/person is responsible for this request?
Greg Whiting - greg.whiting@northgateps.com - Devops for northgate

Review date
2021-12-31

**Comment by AntonyBishop** [comment]
Is this issue still required. The associated repo doesn't appear to exists in Github. Grateful if you could confirm. Many thanks.
