### ISSUE TITLE
Please create an outside collaborator pull request 

### ISSUE THREAD

**Issue by chiaramapellimt** [ministryofjustice/github-collaborators#1894]
### usernames

chiaramapellimt

### names

Chiara Mapelli

### emails

chiara.mapelli@madetech.com

### org

MOJ

### reason

As part of the SIS Team working on the HMPPS API

### added_by

sarah.fernandes@digital.justice.gov.uk

### review_after

2024-10-31

### permission

push

### repositories

hmpps-integration-api
hmpps-integration-api-docs

**Comment by chiaramapellimt** [comment]
Hi, I still can't push to the hmpps-integration-api repo.

**Comment by AntonyBishop** [comment]
Hi @chiaramapellimt  assume this is now resolved? I can see your write access on both repos?

**Comment by chiaramapellimt** [comment]
Hi @AntonyBishop yes I am in, thank you!!
