### ISSUE TITLE
Access request for yjaf-gateway-proxy

### ISSUE THREAD

**Issue by ttipler** [ministryofjustice/github-collaborators#1897]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository/s are you requesting access to (e.g. `money-to-prisoners`)?

yjaf-gateway-proxy

## What is the GitHub username of the person who needs access?

necpgilgunn

## What is their full name?

Philip Gilgunn

## What is their email address?

philip.gilgunn@necsws.com

## What company/organisation do they belong to (e.g. "Department for Education")?

NEC 

## What level of access should they have?

- [x] Read
- [ ] Triage
- [ ] Write
- [ ] Maintain
- [ ] Admin

## Why is this access being requested?

For oversight on the project

## Which MoJ team/person is responsible for this request? This must be a "*.justice.gov.uk" or "*.digital.justice.gov.uk" email address.

This should be an email address `awesome.team@digital.justice.gov.uk`

Team email addresses are preferred, rather than individual email addresses, to make it easier to follow-up at a later date.

antony.bishop@digital.justice.gov.uk

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future from today.

2024-11-09

**Comment by AntonyBishop** [comment]
Awaiting approval from Business owner

**Comment by AntonyBishop** [comment]
https://groups.google.com/a/digital.justice.gov.uk/g/operations-engineering/c/LwjhpMhJ5a0/m/WfZ_5589BwAJ
