### ISSUE TITLE
Bichard7 team 

### ISSUE THREAD

**Issue by richrace** [ministryofjustice/github-collaborators#1909]
Hi, 

The Bichard7 Next team needs all the `review_after` extended for another year, please.

`2023 -> 2024`

For example: https://github.com/ministryofjustice/github-collaborators/compare/main...richrace:github-collaborators:update-bichard7-collaborators

**Comment by AntonyBishop** [comment]
I'll take a look and get those extended.

**Comment by richrace** [comment]
Thank you
