### ISSUE TITLE
Palo Alto Resident Engineer to TechOps

### ISSUE THREAD

**Issue by IanHarvey1** [ministryofjustice/github-collaborators#195]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

terraform-panorama-config

## What is the GitHub username of the person who needs access?

nmatveev

## What is their full name?

Nikolay Matveev

## What is their email address?

nmatveev@paloaltonetworks.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

Palo Alto

## What level of access should they have?

- [ ] Write

## Why is this access being requested?

TechOps Management of Panorama

## Which MoJ team/person is responsible for this request?

MoJ-TechnicalOperations@justice.gov.uk

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

Ian Harvey
ian.harvey1@justice.gov.uk

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

31-03-2022

**Comment by AntonyBishop** [comment]
Hi @IanHarvey1 thanks for raising this issue. We have a slight delay in adding collaborators at the moment due to MoJ running out of Github "seats". We hope to have this addressed soon and will make the changes as soon as possible. Apologies for any inconvenience.

**Comment by IanHarvey1** [comment]
Hi, there is an account for 'iammbari' which can be deleted; will that allow you to add Nikolay?

regards
Ian

**Comment by AntonyBishop** [comment]
That might work. Lets give it a go.

**Comment by AntonyBishop** [comment]
Hi @IanHarvey1 I can't locate a repo called `terraform-panorama-config`. Can you confirm that this repo exists within the MoJ Organisation?

**Comment by IanHarvey1** [comment]
Hi
https://github.com/ministryofjustice/terraform-panorama-config

**Comment by AntonyBishop** [comment]
Hi @IanHarvey1 just running this now. Fingers crossed that no one steals the seat created which the change deploys.

**Comment by AntonyBishop** [comment]
Hi @IanHarvey1 sadly that hasn't worked. We will need to wait for additional licences to be added. Will reopen this issue.

**Comment by IanHarvey1** [comment]
Many thanks @AntonyBishop

**Comment by AntonyBishop** [comment]
Hi @IanHarvey1 Github seats issue has been resolved. Have re-run and the collaborators should now all be added. Any issues please let me know.
