### ISSUE TITLE
Please create an outside collaborator pull request 

### ISSUE THREAD

**Issue by andrewpearce-digital** [ministryofjustice/github-collaborators#1993]
### usernames

weblate

### names

Weblate (bot)

### emails

info@weblate.org

### org

WeblateOrg

### reason

To allow the Weblate App to raise pull requests for translations on a demo translation project

### added_by

andrew.pearce@digital.justice.gov.uk

### review_after

20/02/2025

### permission

pull

### repositories

https://github.com/ministryofjustice/opg-weblate-demo-translation-project

**Comment by andyrogers1973** [comment]
Added opg-weblate-demo-translation-project file to the GitHub collaborators repo and merged.
