### ISSUE TITLE
Please create an outside collaborator pull request 

### ISSUE THREAD

**Issue by zaparka** [ministryofjustice/github-collaborators#2026]
### usernames

eyss1234

### names

Emily Sato

### emails

emily.sato@hmcts.net

### org

hmcts

### reason

C100 application

### added_by

petr.zaparka@hmcts.net

### review_after

2025-01-04

### permission

push

### repositories

https://github.com/ministryofjustice/c100-application

**Comment by AntonyBishop** [comment]
Service is hosted on Cloud Platform so user will need to be a full org member. Invite sent. This is not required.
