### ISSUE TITLE
Add Greg to yjaf-terraform repo

### ISSUE THREAD

**Issue by gregi2n** [ministryofjustice/github-collaborators#2083]
Which MoJ repository/s are you requesting access to (e.g. money-to-prisoners)?

-  yjaf-terraform

What is the GitHub username of the person who needs access?
gregi2n

What is their full name?
Gregory Whiting

What is their email address?
[greg.whiting@necsws.com](mailto:greg.whiting@necsws.com)

What company/organisation do they belong to (e.g. "Department for Education")?
YJAF

What level of access should they have?
Admin

Why is this access being requested?
returning devops - admin access 

Which MoJ team/person is responsible for this request? This must be a ".justice.gov.uk" or ".digital.justice.gov.uk" email address.
This should be an email address [awesome.team@digital.justice.gov.uk](mailto:awesome.team@digital.justice.gov.uk)

Team email addresses are preferred, rather than individual email addresses, to make it easier to follow-up at a later date.

[antony.bishop@digital.justice.gov.uk](mailto:antony.bishop@digital.justice.gov.uk)

Review date
Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future from today.

2025-05-23

**Comment by tamsinforbes** [comment]
Hi it looks like some of the information has not rendered properly; please confirm the required access level, one of 
Read, Triage, Write, Maintain, Admin

And which MoJ team/person is responsible for this request? This must be a ".justice.gov.uk" or ".digital.justice.gov.uk" email address.

Thanks 😊

**Comment by PepperMoJ** [comment]
Just to update on this, we are waiting for approval from David Hall - once approved we will get you added. David is currently out of office and due to return on the 5th of June.

**Comment by PepperMoJ** [comment]
User has now been added to the relevant repositories. Thank you for your patience.
