### ISSUE TITLE
Adding 3 Microsoft Colleagues to an MoJ Github repository as part of the Windows365 engagement in EUCS

### ISSUE THREAD

**Issue by LeanneEmansMoJ** [ministryofjustice/github-collaborators#2194]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository/s are you requesting access to (e.g. `money-to-prisoners`)?

[staff-device-management-virtualdesktop](https://github.com/ministryofjustice/staff-device-management-virtualdesktop)

## What is their full name?

Catrina Feely

Renu Sandy

Nikolay Milyaev 

## What is their email address?

[resandy@microsoft.com](mailto:resandy@microsoft.com)

[nmilyaev@microsoft.com](mailto:nmilyaev@microsoft.com)

[cfeely@microsoft.com](mailto:cfeely@microsoft.com)

## What company/organisation do they belong to (e.g. "Department for Education")?

Microsoft

## What level of access should they have?

- [X] Read
- [X] Triage
- [X] Write
- [ ] Maintain - no
- [ ] Admin - no

## Why is this access being requested?

We have engaged in a Statement of Work with Microsoft to deliver our current MoJO AVD build into a Microsoft Windows 365 product.

## Which MoJ team/person is responsible for this request? This must be a "*.justice.gov.uk" or "*.digital.justice.gov.uk" email address.

Leanne.Emans@justice.gov.uk

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future from today.

01st December 2024 
2024-12-01

**Comment by andyrogers1973** [comment]
Hi Leanne, can you please provide the GitHub ID's for these 3 users - we're unable to process the request without them

**Comment by andyrogers1973** [comment]
Request amended to only 1 user, Nikolay Milyaev.  Changes has been made.
