### ISSUE TITLE
Collaborator without a repository

### ISSUE THREAD

**Issue by bgburton** [ministryofjustice/github-collaborators#2195]
I have been directed here by Julia Lawrence after a collaborator reported that Github had told her she had been removed from the 'MoJ Analytical Services' organisation. The collaborator is also unable to log into the Analytical Platform. I have not used a pull request because the collaborator does not need access to repositories (for now), only to the MoJ Analytical Services or Ministry of Justice organisations so that she may access the Analytical Platform. **If you could also reinstate her access to the AP or advise how that may be requested, I would be grateful.**

## Which MoJ repository/s are you requesting access to (e.g. `money-to-prisoners`)?

Not applicable. The user simply needs access to the organisation so that she may have her Analytical Platform reactivated.

## What is the GitHub username of the person who needs access?

frederica-martijn

## What is their full name?

Frederica Martijn

## What is their email address?

frederica.martijn2021@my.ntu.ac.uk

## What company/organisation do they belong to (e.g. "Department for Education")?

Nottingham Trent University

## What level of access should they have?

- [ ] Read
- [ ] Triage
- [ ] Write
- [ ] Maintain
- [X] Admin

## Why is this access being requested?

It is conceivable that Frederica will want to manage her own repository in the future, although she currently manages her code offline.

## Which MoJ team/person is responsible for this request? This must be a "*.justice.gov.uk" or "*.digital.justice.gov.uk" email address.

Brian.Burton@justice.gov.uk

## Review date

2024-08-29

**Comment by andyrogers1973** [comment]
I have sent an invite to Frederica to reinstate her access to the analytical services organisation

**Comment by bgburton** [comment]
Thanks very much for looking at this, Andy. Frederica says she has access once more so I think we're done!
