### ISSUE TITLE
Please create an outside collaborator pull request For Nathanial Stewart & Simon Givan for Repo :pfs-software-services_terraform

### ISSUE THREAD

**Issue by SteveR2001** [ministryofjustice/github-collaborators#2204]
### usernames

Nathanials
Simon Givan

### names

Nathanial Stewart
Simon Givan

### emails

n.stewart@kainos.com
s.givan@kainos.com

### org

Kainos

### reason

Existing developer

### added_by

stephen.roden1@justice.gov.uk

### review_after

2024-11-30

### permission

pull

### repositories

https://github.com/ministryofjustice/pfs-software-services_terraform

pfs-software-services_terraform

**Comment by AntonyBishop** [comment]
Looks like wrong repo name was used in the original tf module. Will correct it in new PR
