### ISSUE TITLE
Yjsm-ui access required 

### ISSUE THREAD

**Issue by fabiosalvarezza** [ministryofjustice/github-collaborators#2205]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository/s are you requesting access to (e.g. `money-to-prisoners`)?
yjsm-ui

## What is the GitHub username of the person who needs access?
fabiosalvarezza

## What is their full name?
Fabio Salvarezza

## What is their email address?
fabio.salvarezza@necsws.com

## What company/organisation do they belong to (e.g. "Department for Education")?
NEC

## What level of access should they have?

- [x] Read
- [ ] Triage
- [x] Write
- [ ] Maintain
- [ ] Admin

## Why is this access being requested?
Fix Snyk security vulnerabilities exposed by this project

## Which MoJ team/person is responsible for this request? This must be a "*.justice.gov.uk" or "*.digital.justice.gov.uk" email address.
jo.harvey@necsws.com
This should be an email address `awesome.team@digital.justice.gov.uk`

Team email addresses are preferred, rather than individual email addresses, to make it easier to follow-up at a later date.

## Review date
02/09/2025
Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future from today.

**Comment by andyrogers1973** [comment]
Hi Fabio, I've pushed this change up so you should have access soon
