### ISSUE TITLE
New external Interaction Designer

### ISSUE THREAD

**Issue by MichelleGregoryMOJ** [ministryofjustice/github-collaborators#2258]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository/s are you requesting access to (e.g. `money-to-prisoners`)?

Setting up a new prototype for our service

## What is the GitHub username of the person who needs access?

StuBamforthDWP

## What is their full name?

Stuart Bamforth

## What is their email address?

stu.bamforth@guest.vivace.tech

## What company/organisation do they belong to (e.g. "Department for Education")?

Working with Wyser via the Ace platform - working for Private Family Law (Contact: Chris Anderson, Senior Business Analyst and Sam Clarke, project sponsor)

## What level of access should they have?

Write

## Why is this access being requested?

Prototype creation for a new service

## Which MoJ team/person is responsible for this request? This must be a "*.justice.gov.uk" or "*.digital.justice.gov.uk" email address.

michelle.gregory1@justice.gov.uk

More senior sponsor: Chris.Anderson1@justice.gov.uk

## Review date

2024-12-31

**Comment by MichelleGregoryMOJ** [comment]
Hi @AntonyBishop - we are just entering Alpha for a new PFL service so are assuming we will need to create a new repository for our prototype.  Do I need to create that before I can add a third party collaborator?

**Comment by AntonyBishop** [comment]
Hi @MichelleGregoryMOJ. I can confirm the repository will need to be created in the first instance.

**Comment by MichelleGregoryMOJ** [comment]
Hi @AntonyBishop The repository is https://github.com/ministryofjustice/pfl-parent-planner

**Comment by MichelleGregoryMOJ** [comment]
@AntonyBishop - brilliant, thank you so much for sorting this so quickly
