### ISSUE TITLE
Access revoked for a number of team members

### ISSUE THREAD

**Issue by bjpirt** [ministryofjustice/github-collaborators#250]
Hello, 
Today a number of our team were unable to access the repositories specified in the Terraform - please could you check if there have been any issues running this script recently?

**Comment by AntonyBishop** [comment]
Hi @bjpirt please can you advise which users and which repos?

We recently ran a script to tidy up users. This included a large volume of users who had invites to repos but had never accepted them. In those instances the users who not have access in any event due to the expiry of the invites. 

If you can advise names and repos I can check.

**Comment by bjpirt** [comment]
It looks like this is what's happened - a bunch of our users have been removed from the files.

https://github.com/ministryofjustice/github-collaborators/commit/cf95e411a6577213a1c6622585b8944efaf6dc55

I'll make a PR to reinstate them

**Comment by bjpirt** [comment]
I wonder if the 'admin' permission confused the script as both myself an @brettminnie were removed from all repos but we both definitely had full admin access to them before we were removed

**Comment by AntonyBishop** [comment]
It's very possible. We'll take a look. Thanks for the PR.

**Comment by AntonyBishop** [comment]
Will keep open while investigation is ongoing.

**Comment by bjpirt** [comment]
FYI - I've got access again (thanks) and as an admin I wasn't asked to accept an invite. I have full access to the repos now

**Comment by AntonyBishop** [comment]
Hi @bjpirt. Great news.

Out of interest (and possibly why this issue occured), why as a member of the MoJ Org are you being added to these repos as an external collaborator?

**Comment by bjpirt** [comment]
I understood that all users with access to the repo had to go int he collaborators repo - is that not the case?

**Comment by AntonyBishop** [comment]
Hi @bjpirt we have recently refreshed the guidance [here](https://ministryofjustice.github.io/technical-guidance/documentation/standards/storing-source-code.html#github-access).

As a member of MadeTech it is appropriate for you to be an external collaborator. 

But the question for me is why have you been made a member of the MoJ Org?

**Comment by bjpirt** [comment]
I do have an MoJ email address, and have added it to my account so that I can access the Modernisation Platform as it uses GitHub for auth. However, I agree it is more appropriate for me to be an external collaborator. The same applies to @brettminnie

**Comment by AntonyBishop** [comment]
That explains it. We have some similar users for the Cloud Platform. So if I make the accounts just collaborators it'll cut off your Modernisation Platform access. 

That leave us in a halfway house and is something we'll need to think about in our clean-up process. Lets keep things as they are for now. We'll just need to think up how we manage clean-up. 

Many thanks. I'll close this issue.
