### ISSUE TITLE
YJAF UI and Gateway repos for Conway

### ISSUE THREAD

**Issue by joharveynec** [ministryofjustice/github-collaborators#345]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

Sorry, turns out I missed a couple of repos yesterday. Please also grant Conway access to:

yjaf-ui
yjaf-gateway

## What is the GitHub username of the person who needs access?

ConwayNEC

## What is their full name?

Conway Hyacienth

## What is their email address?

conway.hyacienth@necsws.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

NEC

## What level of access should they have?

- [x] Read
- [ ] Triage
- [x] Write
- [ ] Maintain
- [ ] Admin

## Why is this access being requested?

New Front End Developer on YJAF (NEC team)

## Which MoJ team/person is responsible for this request?

Jo Harvey
joanna.harvey@necsws.com

## Review date

03/11/2022

**Comment by liban-hmpps** [comment]
Hi Jo,

I've added in your request and Conway should have access as soon as the action has finished. Conway was already given access to yjaf-gateway in your previous request, so the PR only focuses on granting him access to yjaf-ui.

Do let me know if there are any issues,
Liban
