### ISSUE TITLE
access to yjaf-gateway-proxy repo

### ISSUE THREAD

**Issue by ttipler** [ministryofjustice/github-collaborators#366]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

yjaf-gateway-proxy

## What is the GitHub username of the person who needs access?

gregi2n
ttipler
InFlamesForever

## What is their full name?
Greg Whiting
Thomas Tipler
Richard Came

## What is their email address?

gregory.whiting@necsws.com
thomas.tipler@necsws.com
richard.came@necsws.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

NEC Software Solutions

## What level of access should they have?

Admin for Greg whiting and Thomas Tipler

Read/write for Richard Came

## Why is this access being requested?

Devops guys need access to make app/infra changes

YJAF developer. Needing access to the work on BackEnd coding Tasks

## Which MoJ team/person is responsible for this request?

Thomas Tipler - thomas.tipler@northgateps.com - Devops for northgate

## Review date

2022-12-31

**Comment by ben-al** [comment]
Hi Thomas

I have merged a PR for you, once the below action has finished, access should be granted.

PR: [#370](https://github.com/ministryofjustice/github-collaborators/pull/370)
Action: https://github.com/ministryofjustice/github-collaborators/actions/runs/1503237089

Sorry for the delayed response,

Let me know if there are any issues,

Ben
