### ISSUE TITLE
yjaf-gateway-proxy access request

### ISSUE THREAD

**Issue by ttipler** [ministryofjustice/github-collaborators#372]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

yjaf-gateway-proxy

## What is the GitHub username of the person who needs access?

TomDover-NorthgatePS
richardbradwell

## What is their full name?

Tom Dover
Richard Bradwell

## What is their email address?

tom.dover@northgateps.com
richard.bradwell@necsws.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

NEC

## What level of access should they have?

- [x] Read
- [ ] Triage
- [x] Write
- [ ] Maintain
- [ ] Admin

## Why is this access being requested?

Need access to repo for coding tasks

## Which MoJ team/person is responsible for this request?

This should be in the form `Awesome Team <awesome.team@digital.justice.gov.uk>`.

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

Thomas Tipler - thomas.tipler@northgateps.com - Devops for northgate

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

2022-12-31

**Comment by ben-al** [comment]
Hi Thomas

I have merged a PR for you, once the below action has finished, access should be granted.

PR: [#370](https://github.com/ministryofjustice/github-collaborators/pull/374)
Action: https://github.com/ministryofjustice/github-collaborators/actions/runs/1516371114

Let me know if there are any issues,

Ben
