### ISSUE TITLE
YJAF Repo Access for Javaid Arshad

### ISSUE THREAD

**Issue by joharveynec** [ministryofjustice/github-collaborators#382]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

yjaf-app-template/
yjaf-assets/
yjaf-auth/
yjaf-bands/
yjaf-bed-unlock/
yjaf-case/
yjaf-cmm/
yjaf-conversions/
yjaf-csppi/
yjaf-dal/
yjaf-documents/
yjaf-gateway/
yjaf-mule-hub-connector/
yjaf-mule-mis-processor/
yjaf-nginx-gateway/
yjaf-nginx-pentaho/
yjaf-placements/
yjaf-refdata/
yjaf-returns/
yjaf-sentences/
yjaf-transfers/
yjaf-utilities/
yjaf-views/
yjaf-workflow/
yjaf-yp/
yjsm-hub/
yjsm-hubadmin/
yjaf-ui/
yjsm-hub-svc/

## What is the GitHub username of the person who needs access?

javaidarshadnec

## What is their full name?

Javaid Arshad

## What is their email address?

javaid.arshad@necsws.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

NEC

## What level of access should they have?

- [x] Read
- [ ] Triage
- [x] Write
- [ ] Maintain
- [ ] Admin

## Why is this access being requested?

New YJAF Full Stack Developer

## Which MoJ team/person is responsible for this request?

Jo Harvey joanna.harvey@necsws.com

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

12/12/2022

**Comment by ben-al** [comment]
Hi Jo

I have merged a PR for you, once the below action has finished, access should be granted.

PR: https://github.com/ministryofjustice/github-collaborators/pull/383
Action: https://github.com/ministryofjustice/github-collaborators/actions/runs/1572779147

Let me know if there are any issues,

Ben
