### ISSUE TITLE
Request read access to new memeber

### ISSUE THREAD

**Issue by HughSolTec** [ministryofjustice/github-collaborators#426]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

staff-device-management-windows10-apps

## What is the GitHub username of the person who needs access?

raghavkuchipudi

## What is their full name?

Raghav Kuchipudi

## What is their email address?

raghav.kuchipudi@contentandcloud.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

Content and Cloud

## What level of access should they have?

- [ X] Read
- [ ] Triage
- [ ] Write
- [ ] Maintain
- [ ] Admin

## Why is this access being requested?

New team member / PTTP tech team

## Which MoJ team/person is responsible for this request?

PTTP tech team

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

hugh.dingwall@contentandcloud.com / matthew.white1@justice.gov.uk

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

2022-12-31

**Comment by ben-al** [comment]
Hi Hugh,

Sorry for the delay, had a few problems with our automation.

I have merged a PR for you, once the below action has completed access should be granted.

PR: https://github.com/ministryofjustice/github-collaborators/pull/429
Action: https://github.com/ministryofjustice/github-collaborators/actions/runs/1717656454

Cheers,

Ben
