### ISSUE TITLE
New Admin access to all of YJAF and YSJM repos - Security Review and Admin

### ISSUE THREAD

**Issue by oliviergaubert** [ministryofjustice/github-collaborators#470]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the terraform/ directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

Which MoJ repository are you requesting access to (e.g. money-to-prisoners)?
All yjaf-* repos and yjsm-* repos

What is the GitHub username of the person who needs access?
oliviergaubert

What is their full name?
Olivier Gaubert

What is their email address?
[olivier.gaubert@necsws.com](mailto:olivier.gaubert@necsws.com)

What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?
NEC (formally Northgate Public Services / NPS)

What level of access should they have?
Admin

Why is this access being requested?
Devops guys need access to make app/infra changes and review security issues

Which MoJ team/person is responsible for this request?
Greg Whiting - [greg.whiting@northgateps.com](mailto:greg.whiting@northgateps.com) - Devops for northgate

Review Date
31-12-2022

**Comment by AntonyBishop** [comment]
Hi @oliviergaubert. Due to changes in the process around authorisation of collaborators I need an approval from an MoJ owner of the repos.

Grateful if you could get someone to send me authorisation. Many thanks.

**Comment by jondent** [comment]
Approved - thanks !

**Comment by AntonyBishop** [comment]
Thanks @jondent

**Comment by NickWalt01** [comment]
I've added Oliver, all done.
