### ISSUE TITLE
YJAF and YJSM Repo Access for Drew Maughan

### ISSUE THREAD

**Issue by joharveynec** [ministryofjustice/github-collaborators#471]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

yjsm-ui
yjaf-app-template/
yjaf-assets/
yjaf-auth/
yjaf-bands/
yjaf-bed-unlock/
yjaf-case/
yjaf-cmm/
yjaf-conversions/
yjaf-csppi/
yjaf-dal/
yjaf-documents/
yjaf-gateway/
yjaf-mule-hub-connector/
yjaf-mule-mis-processor/
yjaf-nginx-gateway/
yjaf-nginx-pentaho/
yjaf-placements/
yjaf-refdata/
yjaf-returns/
yjaf-sentences/
yjaf-transfers/
yjaf-utilities/
yjaf-views/
yjaf-workflow/
yjaf-yp/
yjsm-hub/
yjsm-hubadmin/
yjaf-ui/
yjsm-hub-svc/

## What is the GitHub username of the person who needs access?

turtle-nec

## What is their full name?

Drew Maughan

## What is their email address?

drew.maughan@necsws.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

NEC SWS

## What level of access should they have?

- [x] Read
- [ ] Triage
- [x] Write
- [ ] Maintain
- [ ] Admin

## Why is this access being requested?

New NEC Developer

## Which MoJ team/person is responsible for this request? This must be someone with a "*.justice.gov.uk" email address.

Jon Dent jon.dent@justice.gov.uk

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

11/02/2023

**Comment by NickWalt01** [comment]
I've added Drew, all done.
