### ISSUE TITLE
User is in Terraform but not on repository

### ISSUE THREAD

**Issue by bjpirt** [ministryofjustice/github-collaborators#480]
User `sioldham` should have access to [this repo](https://github.com/ministryofjustice/bichard7-next-data/) according to https://github.com/ministryofjustice/github-collaborators/blob/main/terraform/bichard7-next-data.tf#L16 but he doesn't have access

**Comment by AntonyBishop** [comment]
Hi @bjpirt I have manually added `sioldham`. Possibly due to an expired invitation? New invite sent.
