### ISSUE TITLE
Access to yjaf-assets for Sam Mohammed

### ISSUE THREAD

**Issue by ttipler** [ministryofjustice/github-collaborators#481]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

yjaf-assets

## What is the GitHub username of the person who needs access?

SamMohammedUK

## What is their full name?

Sam Mohammed

## What is their email address?

contact@sammohammed.uk

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

NEC SWS

## What level of access should they have?

- [x] Read
- [ ] Triage
- [x] Write
- [ ] Maintain
- [ ] Admin

## Why is this access being requested?

working on the assets project

## Which MoJ team/person is responsible for this request? This must be someone with a "*.justice.gov.uk" email address.

This should be in the form `Awesome Team <awesome.team@digital.justice.gov.uk>`.

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

Jon Dent jon.dent@justice.gov.uk

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

21/02/2023

**Comment by jondent** [comment]
approved
