### ISSUE TITLE
Miriam Gomez-Orozco(Civica)  HMPPS-VCMS repo request access

### ISSUE THREAD

**Issue by izzy-ol** [ministryofjustice/github-collaborators#521]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

hmpps-vcms

## What is the GitHub username of the person who needs access?

miriamgo-civica

## What is their full name?

Miriam Gomez-Orozco

## What is their email address?

Miriam.Gomez-Orozco@civica.co.uk

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

Civica

## What level of access should they have?

- [x] Read
- [ ] Triage
- [x] Write
- [x] Maintain
- [ ] Admin

## Why is this access being requested?

Miriam is a new member of the Civica team who will be working on VCMS

## Which MoJ team/person is responsible for this request? This must be someone with a "*.justice.gov.uk" email address.

Probation Infrastructure AWS Team, awssupportteam@digital.justice.gov.uk

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

Max Lakanu maximillian.lakanu@digital.justice.gov.uk

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

2023-02-27

**Comment by NickWalt01** [comment]
user added to .tf file
