### ISSUE TITLE
Access for C+C Team

### ISSUE THREAD

**Issue by HughSolTec** [ministryofjustice/github-collaborators#538]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

staff-device-management-windows10-mass-storage-controls

## What is the GitHub username of the person who needs access?

cyrusirandoust

## What is their full name?

Cyrus Irandoust

## What is their email address?
cyrus.irandoust@contentandcloud.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

Content and Cloud

## What level of access should they have?

- [ ] Read
- [ ] Triage
- [ ] Write
- [ ] Maintain
- [ x ] Admin

## Why is this access being requested?

Access to repo to create  devops pipelines

## Which MoJ team/person is responsible for this request? This must be someone with a "*.justice.gov.uk" email address.

Matthew.White1@justice.gov.uk

## Review date

02/09/2022

**Comment by ben-al** [comment]
Hi Hugh,

I have created a PR for you, once it is merged, access will be granted.

PR: https://github.com/ministryofjustice/github-collaborators/pull/539

Cheers,

Ben

**Comment by cyrusirandoust** [comment]
Hi @ben-al I can see both PR done, terraform run done, but I still don't have admin access, can't run my pipeline, etc.
