### ISSUE TITLE
YJAF Gateway Proxy repo access for Jon Dent

### ISSUE THREAD

**Issue by joharveynec** [ministryofjustice/github-collaborators#553]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

https://github.com/ministryofjustice/yjaf-gateway-proxy

## What is the GitHub username of the person who needs access?

jondent

## What is their full name?

Jon Dent

## What is their email address?

[Jon.Dent@yjb.gov.uk](mailto:Jon.Dent@yjb.gov.uk)

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

YJB

## What level of access should they have?

- [x] Read
- [ ] Triage
- [x] Write
- [ ] Maintain
- [x] Admin

## Why is this access being requested?

Required as part of gateway proxy development and rollout

## Which MoJ team/person is responsible for this request? This must be someone with a "*.justice.gov.uk" email address.

Jon Dent
[jon.dent@justice.gov.uk](mailto:jon.dent@justice.gov.uk)

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

14/03/2023

**Comment by jondent** [comment]
Clearly I'm approving for myself here ! Hope that's ok :-)

**Comment by NickWalt01** [comment]
Hi, yes that is ok, :)

**Comment by NickWalt01** [comment]
Hi @jondent do you have a MoJ email address?

**Comment by NickWalt01** [comment]
can you ping me an email from that account please? nick.walters@digital.justice.gov.uk
I cannot find you in the email system or see you as a full moj org member on GH.

**Comment by jondent** [comment]
Sent you email.

**Comment by NickWalt01** [comment]
Thank you, just double checking, I'll push the PR through. 

Do you have a or did have a MoJ Org GH account?

**Comment by NickWalt01** [comment]
Thanks for confirming Jon, I think this is a special case that Tony is okay with
