### ISSUE TITLE
Request access to yjaf-gateway-proxy for 

### ISSUE THREAD

**Issue by ttipler** [ministryofjustice/github-collaborators#563]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

yjaf-gateway-proxy

## What is the GitHub username of the person who needs access?

javaidarshadnec

## What is their full name?

Javaid Arshad

## What is their email address?

javaid.arshad@necsws.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

NEC SWS

## What level of access should they have?

- [x] Read
- [ ] Triage
- [x] Write
- [ ] Maintain
- [ ] Admin

## Why is this access being requested?

For work on the gateway-proxy project

## Which MoJ team/person is responsible for this request? This must be someone with a "*.justice.gov.uk" email address.

This should be in the form `Awesome Team <awesome.team@digital.justice.gov.uk>`.

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

Jon Dent jon.dent@justice.gov.uk

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

23/03/2023

**Comment by ben-al** [comment]
Hi Thomas,

I have opened a PR for you, when it merges, access will be granted.

PR: https://github.com/ministryofjustice/github-collaborators/pull/565

Cheers,

Ben
