### ISSUE TITLE
access to yjaf-transitions for Greg and Thomas

### ISSUE THREAD

**Issue by ttipler** [ministryofjustice/github-collaborators#569]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

yjaf-transitions

## What is the GitHub username of the person who needs access?

ttipler
gregi2n

## What is their full name?

Thomas Tipler
Gregory Whiting

## What is their email address?

thomas.tipler@necsws.com
greg.whiting@necsws.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

NEC SWS

## What level of access should they have?

- [ ] Read
- [ ] Triage
- [ ] Write
- [ ] Maintain
- [x] Admin

## Why is this access being requested?

Working on pipeline for deployment of microservice

## Which MoJ team/person is responsible for this request? This must be someone with a "*.justice.gov.uk" email address.

This should be in the form `Awesome Team <awesome.team@digital.justice.gov.uk>`.

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

Jon Dent jon.dent@justice.gov.uk

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

24/03/2023

**Comment by jondent** [comment]
approved for both - thanks

**Comment by ben-al** [comment]
Hi Thomas,

Nick has opened a PR for you, once its merged access will be granted.

PR: https://github.com/ministryofjustice/github-collaborators/pull/570

Cheers,

Ben
