### ISSUE TITLE
Invitation expired for `moj-cjse-bichard7`

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/github-collaborators#577]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

moj-cjse-bichard7

## What is the GitHub username of the person who needs access?

jaskaransarkaria

## What is their full name?

jaskaran sarkaria

## What is their email address?

jazz.sarkaria@madetech.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

MadeTech

I am in the terraform but my invitation to the repo expired could I have another one please?

**Comment by NickWalt01** [comment]
Hello jaskaran
I have added you to the repo
