### ISSUE TITLE
Add C+C resource

### ISSUE THREAD

**Issue by calkin** [ministryofjustice/github-collaborators#586]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

staff-device-management-windows10-apps

## What is the GitHub username of the person who needs access?

JCalkin

## What is their full name?

Joshua Calkin

## What is their email address?

josh.calkin@contentandcloud.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

Content + Cloud

## What level of access should they have?

- [x] Read
- [ ] Triage
- [x] Write
- [ ] Maintain
- [ ] Admin

## Why is this access being requested?

Working on new VICTOR feature 

## Which MoJ team/person is responsible for this request? This must be someone with a "*.justice.gov.uk" email address.

Matthew.white1@justice.gov.uk

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

PTTP

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

2022-05-20

**Comment by NickWalt01** [comment]
Hello calkin, you have already been added to the file, can you check the details are correct please? https://github.com/ministryofjustice/github-collaborators/blob/49475bfd10dd9653168878f8fd8c693e23fd1a78/terraform/staff-device-management-windows10-apps.tf#L46

**Comment by NickWalt01** [comment]
Your also have a pending invite to that repo sent to you via email at some point

**Comment by calkin** [comment]
The details are correct, the invite has expired.

**Comment by NickWalt01** [comment]
I'' remove you and add you again and a new invite will be sent out

**Comment by NickWalt01** [comment]
can you try now and let me know please?

**Comment by calkin** [comment]
perfect, thankyou

**Comment by NickWalt01** [comment]
okay thanks
