### ISSUE TITLE
access request 

### ISSUE THREAD

**Issue by calkin** [ministryofjustice/github-collaborators#592]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

staff-device-management-intune-scripts-prod
staff-device-management-intune-scripts

## What is the GitHub username of the person who needs access?

calkin

## What is their full name?

Joshua Calkin

## What is their email address?

josh.calkin@contentandcloud.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

Content+Cloud

## What level of access should they have?

- [x] Read
- [ ] Triage
- [x] Write
- [ ] Maintain
- [ ] Admin

## Why is this access being requested?

VICTOR development

## Which MoJ team/person is responsible for this request? This must be someone with a "*.justice.gov.uk" email address.

Matthew.white1@justice.gov.uk

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

PTTP

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

2022-04-13

**Comment by NickWalt01** [comment]
@calkin Hi you have an email invite to [staff-device-management-intune-scripts](https://github.com/ministryofjustice/staff-device-management-intune-scripts) I cannot add or remove you from that repo directly, I would have to create a branch to remove you from the file and other to add you again.

**Comment by NickWalt01** [comment]
@calkin you have write access to staff-device-management-intune-scripts-prod

**Comment by AntonyBishop** [comment]
Blocked - Awaiting user response.
