### ISSUE TITLE
New starter Repo Access

### ISSUE THREAD

**Issue by jondent** [ministryofjustice/github-collaborators#622]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

All YJAF repos - 33 in total

## What is the GitHub username of the person who needs access?

AndrewTRichards

## What is their full name?

Andrew Richards

## What is their email address?

a.t.richards@btopenworld.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

NEC Software Solutions

## What level of access should they have?

- [ ] Read
- [ ] Triage
- [ ] Write
- [ ] Maintain
- [ X] Admin

## Why is this access being requested?

New starter (well returning Dev) working on all YJAF projects etc

## Which MoJ team/person is responsible for this request? This must be someone with a "*.justice.gov.uk" email address.

This should be in the form `Awesome Team <awesome.team@digital.justice.gov.uk>`.

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

jon.dent@justice.gov.uk

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

2023-05-26

**Comment by jondent** [comment]
@AntonyBishop - request made on Angus behalf. Would appreciate a quick turnaround as Andrew is picking up a BAU issue asap - cheers Jon

**Comment by NickWalt01** [comment]
@jondent the terraform run completed successfully so the user should have invites to those repo's
