### ISSUE TITLE
New developer repo access request - Vikas Omar

### ISSUE THREAD

**Issue by javaidarshadnec** [ministryofjustice/github-collaborators#626]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

yjaf-assets
yjaf-yp
yjaf-workflow
yjaf-views
yjaf-placements
yjaf-refdata
yjaf-transfers
yjaf-conversions
yjaf-sentences
yjaf-returns
yjaf-gateway
yjaf-documents
yjaf-dal
yjaf-case
yjaf-bed-unlock
yjaf-bands
yjaf-auth
yjaf-transitions
yjaf-serious-incidents
yjaf-mule-hub-connector
yjaf-mule-mis-processor

## What is the GitHub username of the person who needs access?

vikasnecsws 

## What is their full name?

Vikas Omar

## What is their email address?

vikas.omar@necsws.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

YJAF (new developer)

## What level of access should they have?

- [ ] Read
- [ ] Triage
- [ ] Write
- [ ] Maintain
- [x ] Admin

## Why is this access being requested?

Vikas is a new developer who has just joined the team

## Which MoJ team/person is responsible for this request? This must be someone with a "*.justice.gov.uk" email address.

This should be in the form `Awesome Team <awesome.team@digital.justice.gov.uk>`.

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

antony.bishop@digital.justice.gov.uk 

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

2023-06-07

**Comment by jondent** [comment]
Vikas is a new NEC back end dev for YJB - Approved

**Comment by jondent** [comment]
@NickWalt01 The renewals for Vasil are approved, as they are for djv72 (David Vincent). The collaborator, richardbradwell should be removed from all repos as he has left NEC
