### ISSUE TITLE
bichard7-next-ui collaborator access

### ISSUE THREAD

**Issue by tomvaughan77** [ministryofjustice/github-collaborators#674]
Hiya! I (`tomvaughan77`) previously has had access to this repo: https://github.com/ministryofjustice/bichard7-next-ui

I'm in the terraform, but I'm not listed as a collaborator on the repo. Please could I get re-added?

**Comment by NickWalt01** [comment]
Is this the correct email? tom.vaughan@madetech.com

**Comment by tomvaughan77** [comment]
Yes it is, I did get an invite - but it says that it's expired

**Comment by tomvaughan77** [comment]
All sorted. @NickWalt01 thank you very much 💯 🙇
