### ISSUE TITLE
Add user to group

### ISSUE THREAD

**Issue by bjpirt** [ministryofjustice/github-collaborators#696]
Not sure if this is the best place to open this, but please could you add the user @tomvaughan77 to the `bichard7-next-ui-admin-team` in [this repo](https://github.com/ministryofjustice/bichard7-next-ui). He has added his MoJ email address to his account.

**Comment by NickWalt01** [comment]
Hi @bjpirt can you provide Tom's moj email address please and I will send out an invite to become a full org member, then I can add him to the team

**Comment by tomvaughan77** [comment]
Hi @NickWalt01, email is `Tom.Vaughan1@justice.gov.uk`

**Comment by NickWalt01** [comment]
Hi @tomvaughan77 thanks, have sent out an invite, the single sign on doesnt work with the justice email account, but you should still be able get access to GH and set up 2FA
