### ISSUE TITLE
Access request for yjaf-datateam

### ISSUE THREAD

**Issue by javaidarshadnec** [ministryofjustice/github-collaborators#706]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

https://github.com/ministryofjustice/yjaf-datateam

## What is the GitHub username of the person who needs access?
javaidarshadnec

## What is their full name?

Javaid Arshad

## What is their email address?

javaid.arshad@necsws.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

NEC

## What level of access should they have?

- [ ] Read
- [ ] Triage
- [ ] Write
- [ ] Maintain
- [X ] Admin

## Why is this access being requested?

Requesting access so I can perhaps start sharing DB workload with Andrew

## Which MoJ team/person is responsible for this request? This must be someone with a "*.justice.gov.uk" email address.

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

Jon.Dent@yjb.gov.uk

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

31/08/2023

**Comment by AntonyBishop** [comment]
Seeking approval from owner.

**Comment by jondent** [comment]
Approved ! Ta
