### ISSUE TITLE
Request for yjaf-datateam access

### ISSUE THREAD

**Issue by angelanec** [ministryofjustice/github-collaborators#722]
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the `terraform/` directory.

Please supply all the requested information, so that your request can be processed as quickly as possible.

## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

[yjaf-datateam](https://github.com/ministryofjustice/yjaf-datateam)

## What is the GitHub username of the person who needs access?

angelanec

## What is their full name?

Angela Site

## What is their email address?

angela.site@necsws.com

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

YJAF (new developer)

## What level of access should they have?

- [ ] Read
- [ ] Triage
- [ ] Write
- [ ] Maintain
- [ X] Admin

## Why is this access being requested?

I need to perform CRUD actions on YJAF.

## Which MoJ team/person is responsible for this request? This must be someone with a "*.justice.gov.uk" email address.

This should be in the form `Awesome Team <awesome.team@digital.justice.gov.uk>`.

Team details are preferred, rather than individuals, to make it easier to follow-up at a later date.

[antony.bishop@digital.justice.gov.uk](mailto:antony.bishop@digital.justice.gov.uk)

## Review date

Date after which this collaborator's access should be reviewed. This should be a date in the format: 2021-01-15, no more than one year into the future.

2023-06-07

**Comment by jondent** [comment]
Approved
